# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diggity < Formula
  desc "BOM Diggity’s primary purpose is to ensure the security and integrity of software programs. It incorporates secret analysis allowing the user to secure crucial information before deploying any parts of the application to the public."
  homepage "https://www.carbonetes.com/"
  version "1.3.1"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/carbonetes/diggity/releases/download/v1.3.1/diggity_1.3.1_darwin_arm64.tar.gz"
      sha256 "7da73728317fa6c766637969128c4fb97668797df85fb233267bf5d425c11299"

      def install
        bin.install "diggity"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/carbonetes/diggity/releases/download/v1.3.1/diggity_1.3.1_darwin_amd64.tar.gz"
      sha256 "33052651435f80ef4d331e162d73f4b9eafbe62bb6c0f150097fd086144b68a1"

      def install
        bin.install "diggity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carbonetes/diggity/releases/download/v1.3.1/diggity_1.3.1_linux_arm64.tar.gz"
      sha256 "e24cb65542a16e52049db9340400e0451a6e0c8d6d58a69e3ae197f1f27bec08"

      def install
        bin.install "diggity"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/carbonetes/diggity/releases/download/v1.3.1/diggity_1.3.1_linux_amd64.tar.gz"
      sha256 "8bc46a118ced3a40fae7c46257dbff8e54b143e4ac66728f6b123299c31368c8"

      def install
        bin.install "diggity"
      end
    end
  end
end
